import { useNavigate } from 'react-router-dom';

export default function Terms() {
  const navigate = useNavigate();

  function handleAccept() {
    localStorage.setItem('terms_accepted', 'true');
    navigate('/');
  }

  const sections = [
    {
      title: 'No Financial Advice',
      body: 'TRAID Signals provides automated trading signal alerts for informational and educational purposes only. The signals generated by our system do not constitute financial advice, investment recommendations, or solicitation to buy or sell any financial instrument. You should always consult a qualified financial advisor before making any investment decisions.',
    },
    {
      title: 'Past Performance Disclaimer',
      body: 'Past performance of any trading signal, strategy, or system is not indicative of future results. Historical win rates, returns, and performance metrics displayed within the app are based on backtested or simulated data and may not reflect actual real-world trading conditions. Market conditions change, and no system can guarantee profits or prevent losses.',
    },
    {
      title: 'Use at Your Own Risk',
      body: 'Trading cryptocurrencies involves substantial risk of loss and is not suitable for every investor. You are solely responsible for evaluating the merits and risks associated with the use of our signals. By using TRAID Signals, you acknowledge that you may lose some or all of your invested capital, and you agree not to hold TRAID or its affiliates liable for any trading losses.',
    },
    {
      title: 'Data & Privacy',
      body: 'We collect minimal data necessary to operate the service, including your Telegram user ID and signal subscription preferences. We do not store API keys or exchange credentials on our servers. Your data will not be shared with third parties except as required to provide the service functionality.',
    },
  ];

  return (
    <div className="min-h-screen flex flex-col">
      {/* Content */}
      <div className="flex-1 px-7 pt-8 pb-28 animate-fade-in">
        {/* Header */}
        <h1 className="text-[28px] font-bold text-tg-text mb-2" style={{ letterSpacing: '-0.03em' }}>
          Terms & Conditions
        </h1>
        <p className="text-[14px] text-tg-hint mb-8">Please read carefully before continuing</p>

        {/* Body */}
        <div className="space-y-5">
          {sections.map((section) => (
            <div key={section.title} className="card p-5">
              <h3 className="text-[16px] font-semibold text-tg-text mb-2" style={{ letterSpacing: '-0.01em' }}>
                {section.title}
              </h3>
              <p className="text-[14px] text-tg-hint leading-relaxed">
                {section.body}
              </p>
            </div>
          ))}
        </div>
      </div>

      {/* Sticky bottom button */}
      <div className="fixed bottom-0 left-0 right-0 p-5 bg-gradient-to-t from-tg-bg via-tg-bg to-transparent pt-8">
        <button
          type="button"
          onClick={handleAccept}
          className="w-full bg-tg-button text-tg-button-text text-[15px] font-semibold rounded-2xl py-4 pressable shadow-sm"
        >
          I Accept
        </button>
      </div>
    </div>
  );
}
